sql:
  host: 'localhost'
  port: 3306
  password: ''
  database: 'HubExtended'
  username: 'root'
system:
  chatFormat: ''
  plugin_prefix: '&7[&dHubExtended v1.0&7] &r'
  join_message: '&7[&a+&7] '
  leave_message: '&7[&c-&7] '
players:
minigames:
  oitc:
    items:
      bow:
        name: '&aOne shot one kill'


