name: Hub Extended
version: 1.0
main: me.streafe.HubExtended.HubExtended
author: Streafe

commands:
  connect:
    usage: /<command>
    default: true
  friend:
    aliases: [f]
    default: true
  msg:
    aliases: [r, m]
    description: Send a message across servers
    default: true
  minigames:
    default: true
    usage: /<command>
  hub:
    default: true
  sethub:
    default: op
  settings:
    default: true
  luckychest:
    default: true
    aliases: [lc, openchest]
