name: Hub Extended
version: 1.0.5
main: me.streafe.HubExtended.HubExtended
author: Streafe
api-version: 1.0

commands:
  duels:
    usage: /<command>
    default: true
  connect:
    usage: /<command>
    default: true
  friend:
    aliases: [f]
    default: true
  msg:
    aliases: [r, m]
    description: Send a message across servers
    default: true
  minigames:
    default: true
    usage: /<command>
  hub:
    default: true
  sethub:
    default: op
  settings:
    default: true
  luckychest:
    default: true
    aliases: [lc, openchest]
  stats:
    default: true
  help:
    default: true
  oitc:
    default: op
  ranklist:
    default: op
  setrank:
    default: op
